/**
 * Auto-generated by generate-icon-registry.mjs
 * Source: @sanity/icons (235 icons)
 * Generated: 2026-04-21T00:19:16.891Z
 *
 * DO NOT EDIT — re-run the generator after upgrading @sanity/icons:
 *   node generate-icon-registry.mjs --out src/generated/sanity-icons.ts
 *
 * This file has ZERO runtime cost. It contains only types and a
 * compile-time assertion helper. Nothing is imported or executed.
 */

/**
 * Union of every icon exported by @sanity/icons.
 * Use this to get autocomplete when referencing icon names as strings.
 *
 * @example
 * import type { SanityIconName } from './sanity-icons'
 *
 * function getIcon(name: SanityIconName) {
 *   // TypeScript autocompletes all 235 icon names here
 * }
 */
export type SanityIconName =
  | 'AccessDeniedIcon'
  | 'ActivityIcon'
  | 'AddCircleIcon'
  | 'AddCommentIcon'
  | 'AddDocumentIcon'
  | 'AddIcon'
  | 'AddUserIcon'
  | 'ApiIcon'
  | 'ArchiveIcon'
  | 'ArrowDownIcon'
  | 'ArrowLeftIcon'
  | 'ArrowRightIcon'
  | 'ArrowTopRightIcon'
  | 'ArrowUpIcon'
  | 'AsteriskIcon'
  | 'BarChartIcon'
  | 'BasketIcon'
  | 'BellIcon'
  | 'BillIcon'
  | 'BinaryDocumentIcon'
  | 'BlockContentIcon'
  | 'BlockElementIcon'
  | 'BlockquoteIcon'
  | 'BoldIcon'
  | 'BoltIcon'
  | 'BookIcon'
  | 'BookmarkFilledIcon'
  | 'BookmarkIcon'
  | 'BottleIcon'
  | 'BugIcon'
  | 'BulbFilledIcon'
  | 'BulbOutlineIcon'
  | 'CalendarIcon'
  | 'CaseIcon'
  | 'ChartUpwardIcon'
  | 'CheckmarkCircleIcon'
  | 'CheckmarkIcon'
  | 'ChevronDownIcon'
  | 'ChevronLeftIcon'
  | 'ChevronRightIcon'
  | 'ChevronUpIcon'
  | 'CircleIcon'
  | 'ClipboardIcon'
  | 'ClipboardImageIcon'
  | 'ClockIcon'
  | 'CloseCircleIcon'
  | 'CloseIcon'
  | 'CodeBlockIcon'
  | 'CodeIcon'
  | 'CogIcon'
  | 'CollapseIcon'
  | 'ColorWheelIcon'
  | 'CommentIcon'
  | 'ComponentIcon'
  | 'ComposeIcon'
  | 'ComposeSparklesIcon'
  | 'ConfettiIcon'
  | 'ControlsIcon'
  | 'CopyIcon'
  | 'CreditCardIcon'
  | 'CropIcon'
  | 'CubeIcon'
  | 'DashboardIcon'
  | 'DatabaseIcon'
  | 'DesktopIcon'
  | 'DiamondIcon'
  | 'DocumentIcon'
  | 'DocumentPdfIcon'
  | 'DocumentRemoveIcon'
  | 'DocumentSheetIcon'
  | 'DocumentTextIcon'
  | 'DocumentVideoIcon'
  | 'DocumentWordIcon'
  | 'DocumentZipIcon'
  | 'DocumentsIcon'
  | 'DotIcon'
  | 'DoubleChevronDownIcon'
  | 'DoubleChevronLeftIcon'
  | 'DoubleChevronRightIcon'
  | 'DoubleChevronUpIcon'
  | 'DownloadIcon'
  | 'DragHandleIcon'
  | 'DropIcon'
  | 'EarthAmericasIcon'
  | 'EarthGlobeIcon'
  | 'EditIcon'
  | 'EllipsisHorizontalIcon'
  | 'EllipsisVerticalIcon'
  | 'EmptyIcon'
  | 'EnterIcon'
  | 'EnterRightIcon'
  | 'EnvelopeIcon'
  | 'EqualIcon'
  | 'ErrorFilledIcon'
  | 'ErrorOutlineIcon'
  | 'ErrorScreenIcon'
  | 'ExpandIcon'
  | 'EyeClosedIcon'
  | 'EyeOpenIcon'
  | 'FaceHappyIcon'
  | 'FaceIndifferentIcon'
  | 'FaceSadIcon'
  | 'FeedbackIcon'
  | 'FilterIcon'
  | 'FolderIcon'
  | 'GenerateIcon'
  | 'GithubIcon'
  | 'GroqIcon'
  | 'HashIcon'
  | 'HeartFilledIcon'
  | 'HeartIcon'
  | 'HelpCircleIcon'
  | 'HighlightIcon'
  | 'HomeIcon'
  | 'IceCreamIcon'
  | 'ImageIcon'
  | 'ImageRemoveIcon'
  | 'ImagesIcon'
  | 'InboxIcon'
  | 'InfoFilledIcon'
  | 'InfoOutlineIcon'
  | 'InlineElementIcon'
  | 'InlineIcon'
  | 'InsertAboveIcon'
  | 'InsertBelowIcon'
  | 'ItalicIcon'
  | 'JoystickIcon'
  | 'JsonIcon'
  | 'LaunchIcon'
  | 'LeaveIcon'
  | 'LemonIcon'
  | 'LinkIcon'
  | 'LinkRemovedIcon'
  | 'LinkedinIcon'
  | 'ListIcon'
  | 'LockIcon'
  | 'LogoJsIcon'
  | 'LogoTsIcon'
  | 'MarkerIcon'
  | 'MarkerRemovedIcon'
  | 'MasterDetailIcon'
  | 'MenuIcon'
  | 'MicrophoneIcon'
  | 'MicrophoneSlashIcon'
  | 'MobileDeviceIcon'
  | 'MoonIcon'
  | 'NumberIcon'
  | 'OkHandIcon'
  | 'OlistIcon'
  | 'OverageIcon'
  | 'PackageIcon'
  | 'PanelLeftIcon'
  | 'PanelRightIcon'
  | 'PauseIcon'
  | 'PinFilledIcon'
  | 'PinIcon'
  | 'PinRemovedIcon'
  | 'PlayIcon'
  | 'PlugIcon'
  | 'PresentationIcon'
  | 'Progress50Icon'
  | 'Progress75Icon'
  | 'ProjectsIcon'
  | 'PublishIcon'
  | 'ReadOnlyIcon'
  | 'RedoIcon'
  | 'RefreshIcon'
  | 'RemoveCircleIcon'
  | 'RemoveIcon'
  | 'ResetIcon'
  | 'RestoreIcon'
  | 'RetrieveIcon'
  | 'RetryIcon'
  | 'RevertIcon'
  | 'RobotIcon'
  | 'RocketIcon'
  | 'SchemaIcon'
  | 'SearchIcon'
  | 'SelectIcon'
  | 'ShareIcon'
  | 'SortIcon'
  | 'SparkleIcon'
  | 'SparklesIcon'
  | 'SpinnerIcon'
  | 'SplitHorizontalIcon'
  | 'SplitVerticalIcon'
  | 'SquareIcon'
  | 'StackCompactIcon'
  | 'StackIcon'
  | 'StarFilledIcon'
  | 'StarIcon'
  | 'StopIcon'
  | 'StrikethroughIcon'
  | 'StringIcon'
  | 'SunIcon'
  | 'SyncIcon'
  | 'TabletDeviceIcon'
  | 'TagIcon'
  | 'TagsIcon'
  | 'TargetIcon'
  | 'TaskIcon'
  | 'TerminalIcon'
  | 'TextIcon'
  | 'ThLargeIcon'
  | 'ThListIcon'
  | 'ThumbsDownIcon'
  | 'ThumbsUpIcon'
  | 'TiersIcon'
  | 'TimelineIcon'
  | 'ToggleArrowRightIcon'
  | 'TokenIcon'
  | 'TransferIcon'
  | 'TranslateIcon'
  | 'TrashIcon'
  | 'TrendUpwardIcon'
  | 'TriangleOutlineIcon'
  | 'TrolleyIcon'
  | 'TruncateIcon'
  | 'TwitterIcon'
  | 'UlistIcon'
  | 'UnarchiveIcon'
  | 'UnderlineIcon'
  | 'UndoIcon'
  | 'UnknownIcon'
  | 'UnlinkIcon'
  | 'UnlockIcon'
  | 'UnpublishIcon'
  | 'UploadIcon'
  | 'UserIcon'
  | 'UsersIcon'
  | 'VersionsIcon'
  | 'VideoIcon'
  | 'WarningFilledIcon'
  | 'WarningOutlineIcon'
  | 'WrenchIcon';

/**
 * Same as SanityIconName but without the "Icon" suffix.
 * Useful for config objects, serialized data, or shorter notation.
 *
 * @example
 * const config: { icon: SanityIconBaseName } = { icon: 'Edit' } // ✓ autocomplete
 */
export type SanityIconBaseName =
  | 'AccessDenied'
  | 'Activity'
  | 'AddCircle'
  | 'AddComment'
  | 'AddDocument'
  | 'Add'
  | 'AddUser'
  | 'Api'
  | 'Archive'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'ArrowTopRight'
  | 'ArrowUp'
  | 'Asterisk'
  | 'BarChart'
  | 'Basket'
  | 'Bell'
  | 'Bill'
  | 'BinaryDocument'
  | 'BlockContent'
  | 'BlockElement'
  | 'Blockquote'
  | 'Bold'
  | 'Bolt'
  | 'Book'
  | 'BookmarkFilled'
  | 'Bookmark'
  | 'Bottle'
  | 'Bug'
  | 'BulbFilled'
  | 'BulbOutline'
  | 'Calendar'
  | 'Case'
  | 'ChartUpward'
  | 'CheckmarkCircle'
  | 'Checkmark'
  | 'ChevronDown'
  | 'ChevronLeft'
  | 'ChevronRight'
  | 'ChevronUp'
  | 'Circle'
  | 'Clipboard'
  | 'ClipboardImage'
  | 'Clock'
  | 'CloseCircle'
  | 'Close'
  | 'CodeBlock'
  | 'Code'
  | 'Cog'
  | 'Collapse'
  | 'ColorWheel'
  | 'Comment'
  | 'Component'
  | 'Compose'
  | 'ComposeSparkles'
  | 'Confetti'
  | 'Controls'
  | 'Copy'
  | 'CreditCard'
  | 'Crop'
  | 'Cube'
  | 'Dashboard'
  | 'Database'
  | 'Desktop'
  | 'Diamond'
  | 'Document'
  | 'DocumentPdf'
  | 'DocumentRemove'
  | 'DocumentSheet'
  | 'DocumentText'
  | 'DocumentVideo'
  | 'DocumentWord'
  | 'DocumentZip'
  | 'Documents'
  | 'Dot'
  | 'DoubleChevronDown'
  | 'DoubleChevronLeft'
  | 'DoubleChevronRight'
  | 'DoubleChevronUp'
  | 'Download'
  | 'DragHandle'
  | 'Drop'
  | 'EarthAmericas'
  | 'EarthGlobe'
  | 'Edit'
  | 'EllipsisHorizontal'
  | 'EllipsisVertical'
  | 'Empty'
  | 'Enter'
  | 'EnterRight'
  | 'Envelope'
  | 'Equal'
  | 'ErrorFilled'
  | 'ErrorOutline'
  | 'ErrorScreen'
  | 'Expand'
  | 'EyeClosed'
  | 'EyeOpen'
  | 'FaceHappy'
  | 'FaceIndifferent'
  | 'FaceSad'
  | 'Feedback'
  | 'Filter'
  | 'Folder'
  | 'Generate'
  | 'Github'
  | 'Groq'
  | 'Hash'
  | 'HeartFilled'
  | 'Heart'
  | 'HelpCircle'
  | 'Highlight'
  | 'Home'
  | 'IceCream'
  | 'Image'
  | 'ImageRemove'
  | 'Images'
  | 'Inbox'
  | 'InfoFilled'
  | 'InfoOutline'
  | 'InlineElement'
  | 'Inline'
  | 'InsertAbove'
  | 'InsertBelow'
  | 'Italic'
  | 'Joystick'
  | 'Json'
  | 'Launch'
  | 'Leave'
  | 'Lemon'
  | 'Link'
  | 'LinkRemoved'
  | 'Linkedin'
  | 'List'
  | 'Lock'
  | 'LogoJs'
  | 'LogoTs'
  | 'Marker'
  | 'MarkerRemoved'
  | 'MasterDetail'
  | 'Menu'
  | 'Microphone'
  | 'MicrophoneSlash'
  | 'MobileDevice'
  | 'Moon'
  | 'Number'
  | 'OkHand'
  | 'Olist'
  | 'Overage'
  | 'Package'
  | 'PanelLeft'
  | 'PanelRight'
  | 'Pause'
  | 'PinFilled'
  | 'Pin'
  | 'PinRemoved'
  | 'Play'
  | 'Plug'
  | 'Presentation'
  | 'Progress50'
  | 'Progress75'
  | 'Projects'
  | 'Publish'
  | 'ReadOnly'
  | 'Redo'
  | 'Refresh'
  | 'RemoveCircle'
  | 'Remove'
  | 'Reset'
  | 'Restore'
  | 'Retrieve'
  | 'Retry'
  | 'Revert'
  | 'Robot'
  | 'Rocket'
  | 'Schema'
  | 'Search'
  | 'Select'
  | 'Share'
  | 'Sort'
  | 'Sparkle'
  | 'Sparkles'
  | 'Spinner'
  | 'SplitHorizontal'
  | 'SplitVertical'
  | 'Square'
  | 'StackCompact'
  | 'Stack'
  | 'StarFilled'
  | 'Star'
  | 'Stop'
  | 'Strikethrough'
  | 'String'
  | 'Sun'
  | 'Sync'
  | 'TabletDevice'
  | 'Tag'
  | 'Tags'
  | 'Target'
  | 'Task'
  | 'Terminal'
  | 'Text'
  | 'ThLarge'
  | 'ThList'
  | 'ThumbsDown'
  | 'ThumbsUp'
  | 'Tiers'
  | 'Timeline'
  | 'ToggleArrowRight'
  | 'Token'
  | 'Transfer'
  | 'Translate'
  | 'Trash'
  | 'TrendUpward'
  | 'TriangleOutline'
  | 'Trolley'
  | 'Truncate'
  | 'Twitter'
  | 'Ulist'
  | 'Unarchive'
  | 'Underline'
  | 'Undo'
  | 'Unknown'
  | 'Unlink'
  | 'Unlock'
  | 'Unpublish'
  | 'Upload'
  | 'User'
  | 'Users'
  | 'Versions'
  | 'Video'
  | 'WarningFilled'
  | 'WarningOutline'
  | 'Wrench';

/**
 * Keyword → icon name mapping for discoverability.
 * Hover over a keyword in your IDE to see which icons match.
 *
 * @example
 * // Hover over 'arrow' to see: ArrowDownIcon | ArrowLeftIcon | ...
 * type ArrowIcons = IconsByKeyword['arrow']
 */
export interface IconsByKeyword {
  above: 'InsertAboveIcon';
  access: 'AccessDeniedIcon';
  activity: 'ActivityIcon';
  add: 'AddCircleIcon' | 'AddCommentIcon' | 'AddDocumentIcon' | 'AddIcon' | 'AddUserIcon';
  americas: 'EarthAmericasIcon';
  api: 'ApiIcon';
  archive: 'ArchiveIcon';
  arrow: 'ArrowDownIcon' | 'ArrowLeftIcon' | 'ArrowRightIcon' | 'ArrowTopRightIcon' | 'ArrowUpIcon' | 'ToggleArrowRightIcon';
  asterisk: 'AsteriskIcon';
  bar: 'BarChartIcon';
  basket: 'BasketIcon';
  bell: 'BellIcon';
  below: 'InsertBelowIcon';
  bill: 'BillIcon';
  binary: 'BinaryDocumentIcon';
  block: 'BlockContentIcon' | 'BlockElementIcon' | 'CodeBlockIcon';
  blockquote: 'BlockquoteIcon';
  bold: 'BoldIcon';
  bolt: 'BoltIcon';
  book: 'BookIcon';
  bookmark: 'BookmarkFilledIcon' | 'BookmarkIcon';
  bottle: 'BottleIcon';
  bug: 'BugIcon';
  bulb: 'BulbFilledIcon' | 'BulbOutlineIcon';
  calendar: 'CalendarIcon';
  card: 'CreditCardIcon';
  case: 'CaseIcon';
  chart: 'BarChartIcon' | 'ChartUpwardIcon';
  checkmark: 'CheckmarkCircleIcon' | 'CheckmarkIcon';
  chevron: 'ChevronDownIcon' | 'ChevronLeftIcon' | 'ChevronRightIcon' | 'ChevronUpIcon' | 'DoubleChevronDownIcon' | 'DoubleChevronLeftIcon' | 'DoubleChevronRightIcon' | 'DoubleChevronUpIcon';
  circle: 'AddCircleIcon' | 'CheckmarkCircleIcon' | 'CircleIcon' | 'CloseCircleIcon' | 'HelpCircleIcon' | 'RemoveCircleIcon';
  clipboard: 'ClipboardIcon' | 'ClipboardImageIcon';
  clock: 'ClockIcon';
  close: 'CloseCircleIcon' | 'CloseIcon';
  closed: 'EyeClosedIcon';
  code: 'CodeBlockIcon' | 'CodeIcon';
  cog: 'CogIcon';
  collapse: 'CollapseIcon';
  color: 'ColorWheelIcon';
  comment: 'AddCommentIcon' | 'CommentIcon';
  compact: 'StackCompactIcon';
  component: 'ComponentIcon';
  compose: 'ComposeIcon' | 'ComposeSparklesIcon';
  confetti: 'ConfettiIcon';
  content: 'BlockContentIcon';
  controls: 'ControlsIcon';
  copy: 'CopyIcon';
  cream: 'IceCreamIcon';
  credit: 'CreditCardIcon';
  crop: 'CropIcon';
  cube: 'CubeIcon';
  dashboard: 'DashboardIcon';
  database: 'DatabaseIcon';
  denied: 'AccessDeniedIcon';
  desktop: 'DesktopIcon';
  detail: 'MasterDetailIcon';
  device: 'MobileDeviceIcon' | 'TabletDeviceIcon';
  diamond: 'DiamondIcon';
  document: 'AddDocumentIcon' | 'BinaryDocumentIcon' | 'DocumentIcon' | 'DocumentPdfIcon' | 'DocumentRemoveIcon' | 'DocumentSheetIcon' | 'DocumentTextIcon' | 'DocumentVideoIcon' | 'DocumentWordIcon' | 'DocumentZipIcon';
  documents: 'DocumentsIcon';
  dot: 'DotIcon';
  double: 'DoubleChevronDownIcon' | 'DoubleChevronLeftIcon' | 'DoubleChevronRightIcon' | 'DoubleChevronUpIcon';
  down: 'ArrowDownIcon' | 'ChevronDownIcon' | 'DoubleChevronDownIcon' | 'ThumbsDownIcon';
  download: 'DownloadIcon';
  drag: 'DragHandleIcon';
  drop: 'DropIcon';
  earth: 'EarthAmericasIcon' | 'EarthGlobeIcon';
  edit: 'EditIcon';
  element: 'BlockElementIcon' | 'InlineElementIcon';
  ellipsis: 'EllipsisHorizontalIcon' | 'EllipsisVerticalIcon';
  empty: 'EmptyIcon';
  enter: 'EnterIcon' | 'EnterRightIcon';
  envelope: 'EnvelopeIcon';
  equal: 'EqualIcon';
  error: 'ErrorFilledIcon' | 'ErrorOutlineIcon' | 'ErrorScreenIcon';
  expand: 'ExpandIcon';
  eye: 'EyeClosedIcon' | 'EyeOpenIcon';
  face: 'FaceHappyIcon' | 'FaceIndifferentIcon' | 'FaceSadIcon';
  feedback: 'FeedbackIcon';
  filled: 'BookmarkFilledIcon' | 'BulbFilledIcon' | 'ErrorFilledIcon' | 'HeartFilledIcon' | 'InfoFilledIcon' | 'PinFilledIcon' | 'StarFilledIcon' | 'WarningFilledIcon';
  filter: 'FilterIcon';
  folder: 'FolderIcon';
  generate: 'GenerateIcon';
  github: 'GithubIcon';
  globe: 'EarthGlobeIcon';
  groq: 'GroqIcon';
  hand: 'OkHandIcon';
  handle: 'DragHandleIcon';
  happy: 'FaceHappyIcon';
  hash: 'HashIcon';
  heart: 'HeartFilledIcon' | 'HeartIcon';
  help: 'HelpCircleIcon';
  highlight: 'HighlightIcon';
  home: 'HomeIcon';
  horizontal: 'EllipsisHorizontalIcon' | 'SplitHorizontalIcon';
  ice: 'IceCreamIcon';
  image: 'ClipboardImageIcon' | 'ImageIcon' | 'ImageRemoveIcon';
  images: 'ImagesIcon';
  inbox: 'InboxIcon';
  indifferent: 'FaceIndifferentIcon';
  info: 'InfoFilledIcon' | 'InfoOutlineIcon';
  inline: 'InlineElementIcon' | 'InlineIcon';
  insert: 'InsertAboveIcon' | 'InsertBelowIcon';
  italic: 'ItalicIcon';
  joystick: 'JoystickIcon';
  js: 'LogoJsIcon';
  json: 'JsonIcon';
  large: 'ThLargeIcon';
  launch: 'LaunchIcon';
  leave: 'LeaveIcon';
  left: 'ArrowLeftIcon' | 'ChevronLeftIcon' | 'DoubleChevronLeftIcon' | 'PanelLeftIcon';
  lemon: 'LemonIcon';
  link: 'LinkIcon' | 'LinkRemovedIcon';
  linkedin: 'LinkedinIcon';
  list: 'ListIcon' | 'ThListIcon';
  lock: 'LockIcon';
  logo: 'LogoJsIcon' | 'LogoTsIcon';
  marker: 'MarkerIcon' | 'MarkerRemovedIcon';
  master: 'MasterDetailIcon';
  menu: 'MenuIcon';
  microphone: 'MicrophoneIcon' | 'MicrophoneSlashIcon';
  mobile: 'MobileDeviceIcon';
  moon: 'MoonIcon';
  number: 'NumberIcon';
  ok: 'OkHandIcon';
  olist: 'OlistIcon';
  only: 'ReadOnlyIcon';
  open: 'EyeOpenIcon';
  outline: 'BulbOutlineIcon' | 'ErrorOutlineIcon' | 'InfoOutlineIcon' | 'TriangleOutlineIcon' | 'WarningOutlineIcon';
  overage: 'OverageIcon';
  package: 'PackageIcon';
  panel: 'PanelLeftIcon' | 'PanelRightIcon';
  pause: 'PauseIcon';
  pdf: 'DocumentPdfIcon';
  pin: 'PinFilledIcon' | 'PinIcon' | 'PinRemovedIcon';
  play: 'PlayIcon';
  plug: 'PlugIcon';
  presentation: 'PresentationIcon';
  progress50: 'Progress50Icon';
  progress75: 'Progress75Icon';
  projects: 'ProjectsIcon';
  publish: 'PublishIcon';
  read: 'ReadOnlyIcon';
  redo: 'RedoIcon';
  refresh: 'RefreshIcon';
  remove: 'DocumentRemoveIcon' | 'ImageRemoveIcon' | 'RemoveCircleIcon' | 'RemoveIcon';
  removed: 'LinkRemovedIcon' | 'MarkerRemovedIcon' | 'PinRemovedIcon';
  reset: 'ResetIcon';
  restore: 'RestoreIcon';
  retrieve: 'RetrieveIcon';
  retry: 'RetryIcon';
  revert: 'RevertIcon';
  right: 'ArrowRightIcon' | 'ArrowTopRightIcon' | 'ChevronRightIcon' | 'DoubleChevronRightIcon' | 'EnterRightIcon' | 'PanelRightIcon' | 'ToggleArrowRightIcon';
  robot: 'RobotIcon';
  rocket: 'RocketIcon';
  sad: 'FaceSadIcon';
  schema: 'SchemaIcon';
  screen: 'ErrorScreenIcon';
  search: 'SearchIcon';
  select: 'SelectIcon';
  share: 'ShareIcon';
  sheet: 'DocumentSheetIcon';
  slash: 'MicrophoneSlashIcon';
  sort: 'SortIcon';
  sparkle: 'SparkleIcon';
  sparkles: 'ComposeSparklesIcon' | 'SparklesIcon';
  spinner: 'SpinnerIcon';
  split: 'SplitHorizontalIcon' | 'SplitVerticalIcon';
  square: 'SquareIcon';
  stack: 'StackCompactIcon' | 'StackIcon';
  star: 'StarFilledIcon' | 'StarIcon';
  stop: 'StopIcon';
  strikethrough: 'StrikethroughIcon';
  string: 'StringIcon';
  sun: 'SunIcon';
  sync: 'SyncIcon';
  tablet: 'TabletDeviceIcon';
  tag: 'TagIcon';
  tags: 'TagsIcon';
  target: 'TargetIcon';
  task: 'TaskIcon';
  terminal: 'TerminalIcon';
  text: 'DocumentTextIcon' | 'TextIcon';
  th: 'ThLargeIcon' | 'ThListIcon';
  thumbs: 'ThumbsDownIcon' | 'ThumbsUpIcon';
  tiers: 'TiersIcon';
  timeline: 'TimelineIcon';
  toggle: 'ToggleArrowRightIcon';
  token: 'TokenIcon';
  top: 'ArrowTopRightIcon';
  transfer: 'TransferIcon';
  translate: 'TranslateIcon';
  trash: 'TrashIcon';
  trend: 'TrendUpwardIcon';
  triangle: 'TriangleOutlineIcon';
  trolley: 'TrolleyIcon';
  truncate: 'TruncateIcon';
  ts: 'LogoTsIcon';
  twitter: 'TwitterIcon';
  ulist: 'UlistIcon';
  unarchive: 'UnarchiveIcon';
  underline: 'UnderlineIcon';
  undo: 'UndoIcon';
  unknown: 'UnknownIcon';
  unlink: 'UnlinkIcon';
  unlock: 'UnlockIcon';
  unpublish: 'UnpublishIcon';
  up: 'ArrowUpIcon' | 'ChevronUpIcon' | 'DoubleChevronUpIcon' | 'ThumbsUpIcon';
  upload: 'UploadIcon';
  upward: 'ChartUpwardIcon' | 'TrendUpwardIcon';
  user: 'AddUserIcon' | 'UserIcon';
  users: 'UsersIcon';
  versions: 'VersionsIcon';
  vertical: 'EllipsisVerticalIcon' | 'SplitVerticalIcon';
  video: 'DocumentVideoIcon' | 'VideoIcon';
  warning: 'WarningFilledIcon' | 'WarningOutlineIcon';
  wheel: 'ColorWheelIcon';
  word: 'DocumentWordIcon';
  wrench: 'WrenchIcon';
  zip: 'DocumentZipIcon';
}

/**
 * Compile-time assertion that a string is a valid icon name.
 * Returns the string narrowed to SanityIconName — zero runtime cost.
 *
 * @example
 * import { iconName } from './sanity-icons'
 * import { EditIcon } from '@sanity/icons' // still a direct import — tree-shakes
 *
 * // Validates at compile time that 'EditIcon' exists:
 * const name = iconName('EditIcon')  // ✓ typed as 'EditIcon'
 * const bad  = iconName('FooIcon')   // ✗ TypeScript error
 */
export function iconName<T extends SanityIconName>(name: T): T {
  return name;
}

/**
 * Same as iconName() but accepts the short form without "Icon" suffix.
 */
export function iconBaseName<T extends SanityIconBaseName>(name: T): T {
  return name;
}

/** Total number of icons available in @sanity/icons. */
export const SANITY_ICON_COUNT = 235 as const;
